name: Build all images

on:
  workflow_call:
    inputs: 
      force_build:
        description: If the build should be forced even if there are no changes
        type: boolean
        required: false
        default: false

jobs:
  build_base_image:
    uses: ./.github/workflows/fake_build_image.yml
    with:
      force_build: ${{ inputs.force_build }}
      image: "base_image"

  print_base_image_outputs:
    needs: [build_base_image]
    runs-on: ubuntu-latest
    steps:
      - name: Print output
        run: |
          echo "${{ toJson(needs.build_base_image.outputs) }}"
      - name: Conditional run
        if: ${{ inputs.force_build || needs.build_base_image.outputs.did_build_image == 'true' }}
        run: |
          echo "Yes"
      
  build_derived_image:
    needs: [build_base_image]
    uses: ./.github/workflows/fake_build_image.yml
    with:
      force_build: ${{ inputs.force_build || needs.build_base_image.outputs.did_build_image == 'true' }}
      image: "derived_image"
