name: Build images
on: 
  push:
    branches:
      - main
      - dev
    paths: images/**
  pull_request:
    branches:
      - main
      - dev
    paths: images/**

jobs:
  print_ref:
    runs-on: ubuntu-latest
    steps:
      - id: print_branch
        run: echo ${GITHUB_REF#refs/*/}
  build_all_images:
    uses: './.github/workflows/build_all_images.yml'
    with:
      force_build: false
