name: Pretend to build image
        
on:
  workflow_call:
    inputs: 
      force_build:
        description: If the build should be forced even if there are no changes
        type: boolean
        required: false
        default: false
      image:
        description: The image to build
        type: string
        required: true
      image_path:
        description: The path to the image
        type: string
        required: false
        default: images/${{ inputs.image }}
    outputs:
      did_build_image:
        description: If the image was built
        value: ${{ jobs.build.outputs.did_build_image }}
        
jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      did_build_image: ${{ steps.build_image.outputs.image_built }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Print path to check for changes
        run: |
          echo "${{ inputs.image_path }}/**"
      - name: Check if files changed
        if: ${{ ! inputs.force_build }}
        uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            image_changed:
              images/${{ inputs.image }}/**

      - name: Build
        id: build_image
        if: ${{ inputs.force_build || steps.changes.outputs.image_changed == 'true' }}
        run: |
          echo "We build ${{ inputs.image }}"
          echo "image_built=true" >> $GITHUB_OUTPUT
      - name: No Build
        if: ${{ !inputs.force_build && steps.changes.outputs.image_changed != 'true' }} 
        run: |
          echo "No build for ${{ inputs.image }}"
