name: Print current directory
        
on:
  workflow_dispatch:
        
jobs:
  print-username:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Print current directory
        run: |
          cd ./
          ls -al
