name: Print current directory
        
on:
  workflow_dispatch:
  workflow_call:
        
jobs:
  print-dir:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Print current directory
        run: |
          cd ./.github/workflows
          ls -al
          echo {{ github.ref }}
