name: Print time and username

on:
  workflow_dispatch:

jobs:
  print_time_and_say_hi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Printing the current time
        uses: ./.github/workflows/print_current_time.yaml@main
      - name: Printing username
        uses: ./.github/workflows/print_username.yaml
        with: 
          username: "Tim"
    
