name: Print time and username

on:
  workflow_dispatch:

jobs:
  print_time_and_say_hi:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Printing the current time
        uses: ./.github/workflows/print_current_time
      - name: Printing username
        uses: ./.github/workflows/print_username
        with: 
          username: "Tim"
    
