name: Print time and username conditionally

on:
  workflow_dispatch:
    inputs:
      should_say_hi:
        description: 'If the print user_name workflow should be used'
        default: true
        required: false
        type: boolean

jobs:
  say_hi:
    runs-on: ubuntu-latest
    outputs:
      did_say_hi: ${{ steps.update_output.outputs.did_say_hi }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4
      - name: Printing the name
        if: ${{ inputs.should_say_hi }}
        uses: ./.github/actions/print_username
        with: 
          username: "Tim"
      - id: update_output
        if: ${{ inputs.should_say_hi }}
        run: echo "did_say_hi=true" >> "$GITHUB_OUTPUT"
      - id: broken_step
        run: cd..
  check_output:
    runs-on: ubuntu-latest
    needs: [say_hi]
    steps:          
      - id: print_output
        env:
          DID_SAY_HI: ${{ needs.say_hi.outputs.did_say_hi }}
        run: |
          echo "Checking the output of say_hi"
          echo "$DID_SAY_HI"
  print_date:
    uses: ./.github/workflows/print_current_time.yaml
    needs: [say_hi]
  print_dir:
    uses: ./.github/workflows/ls_workflow.yml
    needs: [say_hi]
    
