name: Trigger build image
        
on:
  workflow_dispatch:
    inputs: 
      force_build:
        description: If the build should be forced even if there are no changes
        type: boolean
        required: false
        default: false

jobs:
  build_all_images:
    uses: ./.github/workflows/build_all_images.yml
    with:
      force_build: ${{ inputs.force_build }}
